apiVersion: v2
name: trivy-operator-metrics-exporter
description: Exports Kubernetes resources created by Trivy Operator as metrics.
type: application
version: 0.5.0-alpha.3
appVersion: 0.5.0-alpha.3
