image:
  repository: ghcr.io/3lvia/trivy-operator-metrics-exporter
  tag: v0.4.2
  pullPolicy: Always

serviceMonitor:
  enabled: true
#
# muteConfig: |
#   vulnerabilities:
#     - id: CVE-2025-15467
#       namespace: traefik
#       imageName: curlimages/curl

#     - id: CVE-2025-15467
#       namespace: kube-system
