image:
  repository: ghcr.io/3lvia/trivy-operator-metrics-exporter
  tag: v0.5.0
  pullPolicy: Always

serviceMonitor:
  enabled: true

metrics:
  vulnerabilities:
    enabled: true

  configAudits:
    enabled: true

  exposedSecrets:
    enabled: true
#
# extraEnv:
#   - name: OTEL_EXPORTER_OTLP_PROTOCOL
#     value: grpc
#   - name: OTEL_EXPORTER_OTLP_ENDPOINT
#     value: http://otel-collector.monitoring.svc.cluster.local:4317
#
# muteConfig: |
#   vulnerabilities:
#     # Mutes all vulnerabilities with CVE-2025-15467, regardless of the namespace or image.
#     - id: CVE-2025-15467

#     # Mutes all vulnerabilities with CVE-2025-15467 in the "traefik" namespace, regardless of the image.
#     - id: CVE-2025-15467
#       namespace: traefik

#     # Mutes all vulnerabilities with CVE-2025-15467 in any namespace, but only for the "curlimages/curl" image.
#     - id: CVE-2025-15467
#       namespace: traefik
#       imageName: curlimages/curl
