image:
  repository: ghcr.io/3lvia/trivy-operator-metrics-exporter
  tag: v0.4.1
  pullPolicy: Always

serviceMonitor:
  enabled: true

metrics:
  # How often we check update the metrics from CRDs.
  updateInterval: 10m

  # How often the exporter pod is restarted (to reset metrics).
  restartInterval: 1h

  # Should data from VulnerabilityReports be exported as metrics?
  vulnerabilities:
    enabled: true

  # Should data from ConfigAuditReports be exported as metrics?
  configAudits:
    enabled: true

  # Should data from SecretReports be exported as metrics?
  exposedSecrets:
    enabled: true
