apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-operator-metrics-exporter
rules:
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      - "clustercompliancereports"
      - "clustercompliancedetailreports"
      - "clusterconfigauditreports"
      - "clusterinfraassessmentreports"
      - "clusterrbacassessmentreports"
      - "clustersbomreports"
      - "clustervulnerabilityreports"
      - "configauditreports"
      - "exposedsecretreports"
      - "infraassessmentreports"
      - "rbacassessmentreports"
      - "sbomreports"
      - "vulnerabilityreports"
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

