apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: trivy-operator-metrics-exporter
      app.kubernetes.io/part-of: trivy-operator-metrics-exporter

images:
  - name: ghcr.io/3lvia/trivy-operator-metrics-exporter
    newTag: v0.2.2

resources:
  - ./deployment
  - ./monitoring
  - ./rbac
