version: '2'
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - goconst
    - gomodguard
    - mnd
    - noinlineerr
    - prealloc
    - revive
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl
  enable:
    - exhaustruct_v5
    - gomodguard_v2
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
