apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: trivy-operator-metrics-exporter
    app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  name: trivy-operator-metrics-exporter
  namespace: trivy-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: trivy-operator-metrics-exporter
    app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  name: trivy-operator-metrics-exporter
rules:
- apiGroups:
  - aquasecurity.github.io
  resources:
  - clustercompliancereports
  - clustercompliancedetailreports
  - clusterconfigauditreports
  - clusterinfraassessmentreports
  - clusterrbacassessmentreports
  - clustersbomreports
  - clustervulnerabilityreports
  - configauditreports
  - exposedsecretreports
  - infraassessmentreports
  - rbacassessmentreports
  - sbomreports
  - vulnerabilityreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: trivy-operator-metrics-exporter
    app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  name: trivy-operator-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-operator-metrics-exporter
subjects:
- kind: ServiceAccount
  name: trivy-operator-metrics-exporter
  namespace: trivy-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: trivy-operator-metrics-exporter
    app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  name: trivy-operator-metrics-exporter
  namespace: trivy-system
spec:
  ports:
  - name: trivy-operator-metrics-exporter
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: trivy-operator-metrics-exporter
    app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: trivy-operator-metrics-exporter
    app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  name: trivy-operator-metrics-exporter
  namespace: trivy-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: trivy-operator-metrics-exporter
      app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: trivy-operator-metrics-exporter
        app.kubernetes.io/part-of: trivy-operator-metrics-exporter
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: release
        image: ghcr.io/3lvia/trivy-operator-metrics-exporter:v0.2.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        name: trivy-operator-metrics-exporter
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
        supplementalGroups:
        - 1001
      serviceAccountName: trivy-operator-metrics-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: trivy-operator-metrics-exporter
    app.kubernetes.io/part-of: trivy-operator-metrics-exporter
  name: trivy-operator-metrics-exporter
  namespace: trivy-system
spec:
  endpoints:
  - port: trivy-operator-metrics-exporter
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator-metrics-exporter
