{{- if .Values.muteConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trivy-operator-metrics-exporter.name" . }}-mute-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-operator-metrics-exporter.labels" . | nindent 4 }}
data:
  mute.yaml: |-
    {{- .Values.muteConfig | nindent 4 }}
{{- end }}
