apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trivy-operator-metrics-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-operator-metrics-exporter.labels" . | nindent 4 }}
