{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "trivy-operator-metrics-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-operator-metrics-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator-metrics-exporter
  endpoints:
  - port: trivy-operator-metrics-exporter
{{- end }}
