apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trivy-operator-metrics-exporter
  namespace: trivy-system
spec:
  endpoints:
  - port: trivy-operator-metrics-exporter
  selector:
    matchLabels:
      app: trivy-operator-metrics-exporter
