apiVersion: v1
kind: Service
metadata:
  name: trivy-operator-metrics-exporter
  namespace: trivy-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: trivy-operator-metrics-exporter
